[profile.default]
src = "contracts"
out = "out"
optimizer = true
optimizer_runs = 20000
libs = ["lib"]
test = 'test/foundry'
cache_path = 'forge-cache'
fs_permissions = [{ access = "read", path = "./out"}]
evm_version = "shanghai"
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[fmt]
tab_width = 2

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 1000